name: Reusable Flakehub Publish
on: workflow_call
jobs:
  push:
    timeout-minutes: 30 
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          persist-credentials: false

      - name: Setup Nix
        uses: ./.github/actions/setup-nix

      - name: Publish to FlakeHub
        timeout-minutes: 30
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          name: andrewthomaslee/kubefetch
          include-output-paths: true
          rolling: true
          rolling-minor: 9
